[build]
    command = "yarn run build"
    publish = "dist"
    functions = "functions"

[build.environment]
    NODE_VERSION = "10.15"
    YARN_VERSION = "1.16.0"

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy-Report-Only = "default-src https:"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"

    
    


# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404
